version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    volumes:
      - .:/usr/app/
    container_name: psvalidator-api

  unit-test:
    image: golang:1.20
    command: go test -v ./...
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    container_name: psvalidator-unit-test